version: '3.5'

services:

  redis:
    image: redis:5-alpine
    expose:
      - "6379"

  myapp:
    build: 
      context: .
      target: debug
    security_opt:
      - seccomp:unconfined
    environment: 
      PORT: 3000
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app
      - /home/dev/go:/go
    ports:
      - "3000:3000"
      - "2345:2345"
    # command: dlv debug -l :2345 --headless --log --api-version=2 --accept-multiclient
    command: [ "go", "run", "main.go" ]