version: '3.5'

services:

  redis:
    image: redis:5-alpine
    expose:
      - "6379"

  myapp:
    build: 
      context: .
      target: debug
    security_opt:
      - seccomp:unconfined
    environment: 
      PORT: 3000
      REDIS_URL: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    working_dir: /go/src/app
    cap_add: 
      - SYS_PTRACE
    volumes:
      # mount app resource
      - .:/go/src/app
      # for fast development
      - /home/dev/go:/go
    ports:
      - "3000:3000"
      - "2345:2345"
    # For Debug Only
    command: dlv debug -l 0.0.0.0:2345 --headless --log --api-version=2 --accept-multiclient main.go
    # For normal usage
    # command: [ "go", "run", "main.go" ]
    # For live reload
    # command: gin --appPort 3001 --port 3000
    # production
    # command: ./main
