version: '3.5'

services:

  redis:
    image: redis:5-alpine
    expose:
      - "6379"

  # 
  # https://github.com/RediSearch/
  # 
  # docker run --rm --name redis-search -d redislabs/redisearch:2.0.9 
  # docker exec -it redis-search bash
  # HSET movie:11002 title "Star Wars: Episode V - The Empire Strikes Back" plot "After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy." release_year 1980 genre "Action" rating 8.7 votes 1127635 imdb_id tt0080684
  # HSET movie:11003 title "The Godfather" plot "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son." release_year 1972 genre "Drama" rating 9.2 votes 1563839 imdb_id tt0068646
  # HSET movie:11004 title "Heat" plot "A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist." release_year 1995 genre "Thriller" rating 8.2 votes 559490 imdb_id tt0113277
  # HSET "movie:11005" title "Star Wars: Episode VI - Return of the Jedi" genre "Action" votes 906260 rating 8.3 release_year 1983  plot "The Rebels dispatch to Endor to destroy the second Empire's Death Star." ibmdb_id "tt0086190" 
  # FT.CREATE idx:movie ON hash PREFIX 1 "movie:" SCHEMA title TEXT SORTABLE release_year NUMERIC SORTABLE rating NUMERIC SORTABLE genre TAG SORTABLE
  # FT.INFO idx:movie
  # FT.SEARCH idx:movie " %vatr% " LIMIT 0 0
  # HSET "movie:11006" title "Avatar" genre "Action" votes 9000 rating 9.8 release_year 2016  plot "Salam" ibmdb_id "tt000000" 
  # FT.ALTER idx:movie SCHEMA ADD plot TEXT WEIGHT 0.5
  # 
  # redis:
  #   image: redislabs/redisearch:2.0.9
  #   expose:
  #     - "6379"
  # FT.CREATE idx:room ON HASH PREFIX 1 "room:" SCHEMA title TEXT SORTABLE
  # FT.INFO idx:room
  # FT.SEARCH idx:room "" LIMIT 0 10

  match:
    build: 
      context: .
      target: development
    environment: 
      PORT: 3001
      REDIS_URL: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    working_dir: /go/src/app
    cap_add: 
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      # mount app resource
      - .:/go/src/app
      # for fast development
      - /home/dev/go:/go
    ports:
      - "3000:3000"
      - "2345:2345"
    # For Debug Only
    # change env PORT=3000
    # command: dlv debug -l 0.0.0.0:2345 --headless --log --api-version=2 --accept-multiclient main.go
    # For normal usage
    # command: [ "go", "run", "main.go" ]
    # For live reload
    command: gin --appPort 3001 --port 3000  # change env PORT=3001
    # production
    # command: ./main
